---
title: "Every Semester Needs a Plan"
author: "Runhang"
date: "2020-01-11"
output: html_document
---

&emsp;&emsp;<font color=black>A brand new semester and new year just started.... Let me have some plans AND to-do lists, let me also draw me a big picture of gateway towards my PhD and future academia.</font>

<font color=blue>First of all, ask what are the tools I am missing in my toolkit ha?

- Proficient writing skill 
- Oral English
- Have a broad biology background.(Do not be limited to my research area)
- Biotechnique (Molecular, Portein, omic analysis, Nanopore, Metabolomics)

Note: Ranked according to the importance

<font size=8> P </font>lan Ahead: How to I get close and pick up these goals?

To-do list:

- Jan: Present my 2nd poster (1/16); Draft my proposal (Three chapters by the end of the month)

- Feb: Meet with Dr. Liburd and Dr. Hahn, my prospective committe. Discuss about my proposal, ask Liburd where to catch wide D. suzukii, the RNA-seq project

- Mar: (Plan a trip to Austin if not busy) Collect wide SWD, dissect gut, prepare RNA library, Write career plan, submit the CALS scholarship application

- April: Submit UF GSC and CALS travel grant for the beneficial microbes meeting. Also submit the oral presenting. Get ready for project oral presentation!!!

- May: Contact committee memebers for oral presentation. 



