---
title: "思想汇报|我看“三全育人"
author: "Runhang"
date: "2019-03-21"
output: html_document
---
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;<font color=green>我看“三全育人”</font>
---
今年一月初，喜闻我校华中农业大学植物科学技术学院成为“三全育人”的改革试点。华中农大植物科学技术学院作为这所百年老校最古老的一个学院，历经百年的风风雨雨，沧桑变化，从未停止过对教育的探索，对农业人才的培养。这一次，我们在新时代特色社会主义的时代背景下身先士卒，去求索适合我国当前国情的现代化教育体系，总的目标是培养德智体美劳全面发展的共产主义建设者和接班人。

“三全育人”即全员育人、全程育人、全方位育人。少年强则国强，一个国家的教育水平决定了它的未来，因为注重教育，全世界都见证了我国改革开放以来的迅猛发展，为这只东方雄狮的苏醒而感到彷徨。要说中国这几十年的发展离不开大力公派出国深造；精英化的培养高科技人才。那我认为这一次党提出的“三全育人”更是一种脱精英化的教育改革。要说脱精英并不是我们不再去培养学术顶尖，科技顶尖的人才，而是扩大教育的规模，把教育不平等的天平再适当调度，从点，也即是家庭，老师的言传身教教育；到线，即是全程的、媒体化的、社区式的、、远程的教育。再到整个面的全国教育普及，点线面结合全方位渗透，提高下一代中国特色社会主义接班人的综合素质。

前两天哈佛大学新上任的校长巴科先生出访我国，总书记习近平同志在人民大会堂会见了巴科。新中国成立，特别是改革开放这40多年来，加强教育对外开发一直我国所贯彻教育战略。我常常感慨我国古人精妙的处世哲学与文化——“知己知彼，百战不殆”，“他山之石可以攻玉”；又常常愤慨当年清朝闭关锁国，固步自封，最后被帝国列强欺压掠夺。1842年，魏源在《海国图志》里提出的那句“师夷长技以制夷”，明确的提出了像西方人学习的理念，可以说是一次教育思想上谋略起点。我们并不回避时下中美紧张的经济矛盾冲突，特别是作为本身就在美国的留学的中国学生，对中美问题尤为敏感。近几个月，多名科学家因为签证缺席国际大会，中国留学生签证越来越难，中国留学生无疑正在经历[留美签证](https://posts.careerengine.us/p/5c93b3021cc300249e91a148)最黑暗的时期。美国或许忘了国际化和多元化的吸收人才才是他们的领先世界的原因。而此次巴科访问中国，更是代表着美国学术界像中国抛出橄榄枝：因为教育和学术的合作没有国界。



