---
title: Visualize Your Data(1)
author: 'Runhang'
date: '2019-03-24'
slug: visualize-your-data
categories: []
tags: []
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

```{r}
data<-read.csv("primates data.csv")
data ## When we look at this data, we can see there are a lot of NA and we want to get rid of them

vec=is.na(data$Brainwt) ## create a vector to manipulate data-- it is very useful
newdata<-data[!vec,] ## the exclamatory mark "!"" mean "reverse", that means we do not want rows that contain NA. 
newdata 
```

#<font color="green">Now, we get rid of the data we do not want and let us plot our data!</font>
```{r}
plot(x=newdata$Bodywt,y=newdata$Brainwt,pch=19,xlab='Body weight(kg)',ylab='Brain weight(kg)',xlim=c(0,250))
## pch is use for different type of dot, xlab set the x-axis text,xlim set the x-axis length
## Now we want to add text alongside each dot 
text(x=newdata$Bodywt,y=newdata$Brainwt,labels=newdata$Spp,pos=4)

## pos=4 means "right", pos=1 means "under"
```